spring.application.name=api

spring.config.import=optional:file:./.env[.properties]

management.health.mongodb.enabled=false

spring.mongodb.uri=${MONGO_URL}
spring.mongodb.database=${MONGO_DATABASE}

spring.data.redis.url=${REDIS_URL}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mongodb.representation.uuid=standard

jwt.secret=${SECRET}
jwt.issuer=${ISSUER}
jwt.audience=${AUDIENCE}
